name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: User
        uses: lowlighter/metrics@latest
        with:
          filename: .cache/user.svg
          token: ${{ secrets.METRICS_TOKEN }}

      - name: Languages
        uses: lowlighter/metrics@latest
        with:
          filename: .cache/languages.svg
          base: ""
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages: yes
          plugin_languages_limit: 20
          plugin_languages_indepth: yes

      - name: Mildly interesting facts
        uses: lowlighter/metrics@latest
        with:
          filename: .cache/habits-facts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes

      - name: Half-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: .cache/isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
